# Generated by Django 3.2.9 on 2021-11-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('explanation', models.TextField(blank=True, max_length=100)),
                ('item_image', models.ImageField(blank=True, upload_to='#')),
                ('item_price', models.CharField(max_length=50)),
                ('item_state', models.CharField(max_length=50)),
                ('item_receipt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker_name', models.CharField(max_length=50)),
                ('maker_address', models.CharField(max_length=50)),
                ('maker_contact', models.CharField(max_length=50)),
                ('maker_certificate', models.CharField(max_length=50)),
                ('maker_certificate_name', models.CharField(max_length=50)),
            ],
        ),
    ]
