# Generated by Django 3.2.9 on 2021-12-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_auto_20211122_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='computer/images/%Y/%m/%d'),
        ),
    ]
