# Generated by Django 3.2.9 on 2021-12-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_item_head_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_image',
        ),
    ]
