# Generated by Django 3.2.9 on 2021-12-18 13:24

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0007_auto_20211218_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='explanation',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
